# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CAGames' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'Dollar‘

  # Pods for CAGames

  target 'CAGamesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CAGamesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
